services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    image: ghcr.io/makeouthillx32/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3010}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
      - love-models.local:host-gateway
    restart: unless-stopped

  api:
    extends:
      file: docker-compose.api.yaml
      service: api
    restart: unless-stopped

  gpu:
    extends:
      file: docker-compose.gpu.yaml
      service: gpu
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}